### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by RamiMorrar** [dotnet-ad/Spritesheet#3]
I wanted to know if this project still works or not.

**Comment by Kaifungamedev** [comment]
I could not get it to work with monogame 3.8.1, so I'd recommend [Monogame.extended.Animation](https://www.monogameextended.net/docs/features/animations/animations).

**Comment by RamiMorrar** [comment]
> I could not get it to work with monogame 3.8.1, so I'd recommend [Monogame.extended.Animation](https://www.monogameextended.net/docs/features/animations/animations).

This library has been sunset. Pain
